Vjezba.Web/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.DAL;
using Vjezba.Model;

namespace Vjezba.Web.Controllers
{
    public class ClientController : VjezbaControllerBase
    {
        // GET: Client
        public ActionResult Index()
        {
            var model = ClientRepository.All.ToList();

            return View(model);
        }

        [Authorize]
        [Route("klijent/detalji/{id}")]
        public ActionResult Details(int id)
        {
            var model = ClientRepository.Find(id);

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create()
        {
            return View(new ClientDTO());
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create(ClientDTO model)
        {
            if (ModelState.IsValid)
            {
                ClientRepository.InsertDTO(model);
                ClientRepository.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(int id)
        {

            var model = ClientRepository.GetDTO(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult EditPost(ClientDTO formModel)
        {
            if (ModelState.IsValid)
            {
                var modelDb = ClientRepository.GetDTO(formModel.Id);
                if (this.TryUpdateModel(modelDb))
                {
                    ClientRepository.UpdateDTO(modelDb);
                    ClientRepository.Save();

                    return RedirectToAction("Index");
                }
            }

            return View(formModel);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int id)
        {
            ClientRepository.Delete(id);
            ClientRepository.Save();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AddNewCar()
        {
            return PartialView("_SingleCarEdit", new CarDTO());
        }
    }
}

Vjezba.Web/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Model;

namespace Vjezba.Web.Controllers
{
    public class PartController : VjezbaControllerBase
    {
        // GET: Part
        [Authorize]
        public ActionResult Index()
        {
            var model = PartRepository.All.ToList();

            return View(model);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            var model = PartRepository.Find(id);

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create(Part model)
        {
            if (ModelState.IsValid)
            {
                PartRepository.Insert(model);
                PartRepository.Save();
                return RedirectToAction("Create");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(int id)
        {

            var model = PartRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(Part formModel)
        {
            if (ModelState.IsValid)
            {
                var modelDb = PartRepository.Find(formModel.ID);
                if (this.TryUpdateModel(modelDb))
                {
                    PartRepository.Update(modelDb);
                    PartRepository.Save();

                    return RedirectToAction("Index");
                }
            }
            return View(formModel);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int id)
        {
            PartRepository.Delete(id);
            PartRepository.Save();

            return RedirectToAction("Index");
        }
    }
}

Vjezba.Web/Controllers/RepairController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Model;

namespace Vjezba.Web.Controllers
{
    public class RepairController : VjezbaControllerBase
    {
        // GET: Repair
        [Authorize]
        public ActionResult Index()
        {
            var model = RepairRepository.All.ToList();
            return View(model);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            var model = RepairRepository.Find(id);

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create(Repair model)
        {
            if (ModelState.IsValid)
            {
                RepairRepository.Insert(model);
                RepairRepository.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(int id)
        {
            var model = RepairRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(Repair formModel)
        {
            if (ModelState.IsValid)
            {
                var modelDb = RepairRepository.Find(formModel.ID);
                if (this.TryUpdateModel(modelDb))
                {
                    RepairRepository.Update(modelDb);
                    RepairRepository.Save();

                    return RedirectToAction("Index");
                }
            }

            return View(formModel);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int id)
        {
            RepairRepository.Delete(id);
            RepairRepository.Save();

            return RedirectToAction("Index");
        }
    }
}

Vjezba.Web/Controllers/RepairerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Model;

namespace Vjezba.Web.Controllers
{
    [RoutePrefix("serviser")]
    public class RepairerController : VjezbaControllerBase
    {
        // GET: Part
        [Route("svi")]
        [Authorize]
        public ActionResult Index()
        {
            var model = RepairerRepository.All.ToList();

            return View(model);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            var model = RepairerRepository.Find(id);

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Create(Repairer model)
        {
            if (ModelState.IsValid)
            {
                RepairerRepository.Insert(model);
                RepairerRepository.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(int id)
        {

            var model = RepairerRepository.Find(id);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Edit(Repairer formModel)
        {
            if (ModelState.IsValid)
            {
                var modelDb = RepairerRepository.Find(formModel.ID);
                if (this.TryUpdateModel(modelDb))
                {
                    RepairerRepository.Update(modelDb);
                    RepairerRepository.Save();

                    return RedirectToAction("Index");
                }
            }
            return View(formModel);
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Delete(int id)
        {
            RepairerRepository.Delete(id);
            RepairerRepository.Save();

            return RedirectToAction("Index");
        }
    }
}

Vjezba.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Autoservis", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Početna", "Index", "Home")</li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            Radni nalog <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Svi radni nalozi", "Index", "WorkingOrders")</li>
                            <li>@Html.ActionLink("Dodaj radni nalog", "Create", "WorkingOrders")</li>
                        </ul>
                    </li>


                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            Klijenti <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Svi klijenti", "Index", "Client")</li>
                            <li>@Html.ActionLink("Dodaj klijenta", "Create", "Client")</li>
                        </ul>
                    </li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            Dijelovi <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Svi dijelovi", "Index", "Part")</li>
                            <li>@Html.ActionLink("Dodaj dijelove", "Create", "Part")</li>
                        </ul>
                    </li>

                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            Popravci <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Svi popravci", "Index", "Repair")</li>
                            <li>@Html.ActionLink("Dodaj popravak", "Create", "Repair")</li>
                        </ul>
                    </li>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            Serviseri <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Svi serviseri", "Index", "Repairer")</li>
                            <li>@Html.ActionLink("Dodaj servisera", "Create", "Repairer")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Admin", "Index", "Admin" ,new { area = "Admin" }, null)</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET MVC 2015</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Html.Partial("_UICultureSetup")


    @RenderSection("scripts", required: false)
</body>
</html>

Vjezba.Web/Views/Shared/_UICultureSetup.cshtml
@{
    <script type="text/javascript">
        $(function () {
            $('.date-picker').datetimepicker({
                locale: '@System.Threading.Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName',
                format: '@System.Threading.Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern.ToUpper()'
            });
        });
    </script>

    <script type="text/javascript">
        $.validator.methods.date = function (value, element) {
            if (this.optional(element) && (value == '' || value == undefined || value == null))
                return true;

            var shortDatePattern = '@System.Threading.Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern.ToUpper()';

            return moment(value, shortDatePattern).isValid();
        }

        $.validator.methods.number = function (value, element) {
            if (this.optional(element))
                return true;
            if (!isNaN(Globalize.parseFloat(value, '@System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName'))) {
                return true;
            }
            return false;
        }

    </script>

}